/* Generated By:JavaCC: Do not edit this line. MyParser02Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser02Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"a\"",
  };

}
