/* Generated By:JavaCC: Do not edit this line. MyParser11Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser11Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT_CONTROL = 2;
  /** RegularExpression Id. */
  int END_PARA = 3;
  /** RegularExpression Id. */
  int REG_TXT = 4;
  /** RegularExpression Id. */
  int ITALIC_TXT = 5;
  /** RegularExpression Id. */
  int BLANK_LINE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<NOT_CONTROL>",
    "\"\\r\\n\"",
    "<REG_TXT>",
    "<ITALIC_TXT>",
    "<BLANK_LINE>",
  };

}
