/* Generated By:JavaCC: Do not edit this line. MyParser10Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser10Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARA = 2;
  /** RegularExpression Id. */
  int FULL_LINE = 3;
  /** RegularExpression Id. */
  int TXT_LINE = 4;
  /** RegularExpression Id. */
  int END_PARA = 5;
  /** RegularExpression Id. */
  int END_LINE = 6;
  /** RegularExpression Id. */
  int BLANK_LINE = 7;
  /** RegularExpression Id. */
  int POEM = 8;
  /** RegularExpression Id. */
  int INDENT = 9;
  /** RegularExpression Id. */
  int ITALIC = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<PARA>",
    "<FULL_LINE>",
    "<TXT_LINE>",
    "\"\\r\\n\\r\\n\"",
    "\"\\r\\n\"",
    "\"~~~~\\r\\n\\r\\n\"",
    "\"@\"",
    "\"^\"",
    "\"_\"",
  };

}
