/* Generated By:JavaCC: Do not edit this line. MyParser08Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser08Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ITALIC = 2;
  /** RegularExpression Id. */
  int POETRY = 3;
  /** RegularExpression Id. */
  int BLANK_LINE = 4;
  /** RegularExpression Id. */
  int INDENT = 5;
  /** RegularExpression Id. */
  int NL = 6;
  /** RegularExpression Id. */
  int TEXT = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"_\"",
    "\"@\"",
    "\"~~~~\"",
    "\"^\"",
    "\"\\r\\n\"",
    "<TEXT>",
  };

}
