/* Generated By:JavaCC: Do not edit this line. MyParser09Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser09Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK_LINE = 2;
  /** RegularExpression Id. */
  int PARA = 3;
  /** RegularExpression Id. */
  int LINE = 4;
  /** RegularExpression Id. */
  int TEXT = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"~~~~\\r\\n\"",
    "<PARA>",
    "<LINE>",
    "<TEXT>",
  };

}
