/* Generated By:JavaCC: Do not edit this line. MyParser15Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser15Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT_CONTROL = 2;
  /** RegularExpression Id. */
  int NL = 3;
  /** RegularExpression Id. */
  int TEXT = 4;
  /** RegularExpression Id. */
  int ITALIC_TEXT = 5;
  /** RegularExpression Id. */
  int POEM_BEGIN = 6;
  /** RegularExpression Id. */
  int SECOND_NL = 7;
  /** RegularExpression Id. */
  int NEXT_LINE_OF_TEXT = 8;
  /** RegularExpression Id. */
  int POEM = 9;
  /** RegularExpression Id. */
  int POEM_LINE = 10;

  /** Lexical state. */
  int POEM_STATE = 0;
  /** Lexical state. */
  int NL_MANAGER_STATE = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<NOT_CONTROL>",
    "\"\\r\\n\"",
    "<TEXT>",
    "<ITALIC_TEXT>",
    "\"@\"",
    "\"\\r\\n\"",
    "<NEXT_LINE_OF_TEXT>",
    "<POEM>",
    "<POEM_LINE>",
  };

}
