/* Generated By:JavaCC: Do not edit this line. MyParser14Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser14Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT = 2;
  /** RegularExpression Id. */
  int NL_NL = 3;
  /** RegularExpression Id. */
  int NL = 4;
  /** RegularExpression Id. */
  int UNDERSCORE = 5;
  /** RegularExpression Id. */
  int AMPERSAND = 6;
  /** RegularExpression Id. */
  int CARET = 7;
  /** RegularExpression Id. */
  int PIPE = 8;
  /** RegularExpression Id. */
  int TILDE = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<TEXT>",
    "\"\\r\\n\\r\\n\"",
    "\"\\r\\n\"",
    "\"_\"",
    "\"@\"",
    "\"^\"",
    "\"|\"",
    "\"~~~~\"",
  };

}
