/* Generated By:JavaCC: Do not edit this line. MyParser12Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser12Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT_CONTROL = 2;
  /** RegularExpression Id. */
  int NL = 3;
  /** RegularExpression Id. */
  int PARA = 4;
  /** RegularExpression Id. */
  int LINE = 5;
  /** RegularExpression Id. */
  int POEM_BEGIN = 6;
  /** RegularExpression Id. */
  int POEM = 7;
  /** RegularExpression Id. */
  int POEM_LINE = 8;

  /** Lexical state. */
  int POEM_STATE = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<NOT_CONTROL>",
    "\"\\r\\n\"",
    "<PARA>",
    "<LINE>",
    "\"@\"",
    "<POEM>",
    "<POEM_LINE>",
  };

}
