/* Generated By:JavaCC: Do not edit this line. MyParser03Constants.java */
package book.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParser03Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXPECTED_CHAR = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EXPECTED_CHAR>",
  };

}
