/* Generated By:JavaCC: Do not edit this line. BookLexerConstants.java */
package book.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BookLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT_CONTROL = 2;
  /** RegularExpression Id. */
  int NOT_CONTROL_BUT_ALLOW_NL = 3;
  /** RegularExpression Id. */
  int NL_NL = 4;
  /** RegularExpression Id. */
  int NL = 5;
  /** RegularExpression Id. */
  int CHARS = 6;
  /** RegularExpression Id. */
  int TEXT_LINE = 7;
  /** RegularExpression Id. */
  int TEXT = 8;
  /** RegularExpression Id. */
  int ITALIC_TEXT = 9;
  /** RegularExpression Id. */
  int CORRESPONDANCE = 10;
  /** RegularExpression Id. */
  int POEM = 11;
  /** RegularExpression Id. */
  int BLANK_LINE = 12;
  /** RegularExpression Id. */
  int CENTER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<NOT_CONTROL>",
    "<NOT_CONTROL_BUT_ALLOW_NL>",
    "\"\\r\\n\\r\\n\"",
    "\"\\r\\n\"",
    "<CHARS>",
    "<TEXT_LINE>",
    "<TEXT>",
    "<ITALIC_TEXT>",
    "<CORRESPONDANCE>",
    "<POEM>",
    "<BLANK_LINE>",
    "<CENTER>",
  };

}
